module:
  authme: false
  placeholder-api: false
  debug-stick: false
  lag-alert: false
  premium: false
  shart: true

setting:
  placeholder-api:
    prefix:
      missile-wars: false
    footer: "请修改页脚内容！"
  lag-alert:
    max-mspt: 80
    lag-broadcast: |-
      <hover:show_text:'这是实时消息，我们有一个性能监测程序。当服务器运行缓慢时，它会自动发出警告！'>
      <color:#ab1c15><b>[WARNING]服务器当前已过载！此刻MSPT：%mspt%</b></color>
      <b>请即刻离开大型刷怪塔、粘液基地、村民交易所等卡服地点，谢谢合作！</b>
      </hover>
  premium:
    commands:
      - "luckperms user [player] parent add premium"
  shart:
    source: butt
    sharts: 25
  debug-stick:
    excluded_blocks:
      - COMPOSTER
      - CACTUS
      - KELP
      - SUGAR_CANE
      - GRASS_BLOCK
      - ACACIA_LEAVES
      - AZALEA_LEAVES
      - BIRCH_LEAVES
      - DARK_OAK_LEAVES
      - FLOWERING_AZALEA_LEAVES
      - JUNGLE_LEAVES
      - MANGROVE_LEAVES
      - OAK_LEAVES
      - SPRUCE_LEAVES
      - BIG_DRIPLEAF
      - BIG_DRIPLEAF_STEM
      - CHORUS_FLOWER
      - CHORUS_FRUIT
      - CHORUS_PLANT
      - SEA_PICKLE
      - RESPAWN_ANCHOR
      - TRIPWIRE_HOOK
      - TURTLE_EGG
      - BEE_NEST
      - BEEHIVE
      - CAKE
      - SWEET_BERRY_BUSH
      - BEETROOT_SEEDS
      - MELON_SEEDS
      - PUMPKIN_SEEDS
      - WHEAT_SEEDS
      - CHEST
      - END_PORTAL_FRAME
      - END_PORTAL
      - PISTON
      - PISTON_HEAD
      - SNOW
      - SCULK_SENSOR
      - SCULK_SCHRIEKER
      - ACACIA_SLAB
      - ANDESITE_SLAB
      - BIRCH_SLAB
      - BLACKSTONE_SLAB
      - BRICK_SLAB
      - COBBLED_DEEPSLATE_SLAB
      - COBBLESTONE_SLAB
      - CRIMSON_SLAB
      - CUT_COPPER_SLAB
      - CUT_RED_SANDSTONE_SLAB
      - CUT_SANDSTONE_SLAB
      - DARK_OAK_SLAB
      - DARK_PRISMARINE_SLAB
      - DEEPSLATE_TITLE_SLAB
      - DIORITE_SLAB
      - END_STONE_BRICK_SLAB
      - EXPOSED_CUT_COPPER_SLAB
      - GRANITE_SLAB
      - JUNGLE_SLAB
      - MANGROVE_SLAB
      - MOSSY_STONE_BRICK_SLAB
      - MUD_BRICK_SLAB
      - NETHER_BRICK_SLAB
      - OAK_SLAB
      - OXIDIZED_CUT_COPPER_SLAB
      - PETRIFIED_OAK_SLAB
      - POLISHED_ANDESITE_SLAB
      - POLISHED_BLACKSTONE_BRICK_SLAB
      - POLISHED_BLACKSTONE_SLAB
      - POLISHED_DEEPSLATE_SLAB
      - POLISHED_DIORITE_SLAB
      - PRISMARINE_BRICK_SLAB
      - PRISMARINE_SLAB
      - PURPUR_SLAB
      - QUARTZ_SLAB
      - RED_NETHER_BRICK_SLAB
      - RED_SANDSTONE_SLAB
      - SANDSTONE_SLAB
      - SMOOTH_QUARTZ_SLAB
      - SMOOTH_RED_SANDSTONE_SLAB
      - SMOOTH_STONE_SLAB
      - SPRUCE_SLAB
      - STONE_BRICK_SLAB
      - STONE_SLAB
      - WARPED_SLAB
      - WAXED_CUT_COPPER_SLAB
      - WAXED_EXPOSED_CUT_COPPER_SLAB
      - WAXED_OXIDIZED_CUT_COPPER_SLAB
      - WAXED_WEATHERED_CUT_COPPER_SLAB
      - WEATHERED_CUT_COPPER_SLAB


