name: ToiletCore
version: "${version}"
main: net.toiletmc.toiletcore.ToiletCore
api-version: "1.21"
authors: [ TheLittle_Yang, zty012 ]

softdepend:
  - "AuthMe"
  - "spark"
  - "LuckPerms"
  - "CMI"
  - "Magic"

description: Plugin for ToiletMC Server
website: https://toiletmc.net

commands:
  toiletcore:
    aliases: [ tc ]
    permission: toiletcore.command
  shart:
    aliases: [ shit, poop, poo ]
    permission: toiletcore.command.shart
  hook:
    permission: toiletcore.command.hook
  cdk:
    permission: toiletcore.command.cdk
  qq:
    permission: toiletcore.command.qq

permissions:
  toiletcore.admin:
    default: op
  toiletcore.admin.cdk:
    default: op
  toiletcore.command:
    default: true
  toiletcore.command.toggle:
    default: true
  toiletcore.command.shart:
    default: true
  toiletcore.command.shart.others:
    default: op
  toiletcore.command.hook:
    default: true
  toiletcore.command.cdk:
    default: true
  toiletcore.command.qq:
    default: true
  toiletcore.bypass.tpguard:
    default: op
