name: ToiletCore
version: '${version}'
main: net.toiletmc.toiletcore.ToiletCore
api-version: '1.19'
authors: [TheLittle_Yang]
softdepend:
  - AuthMe
  - PlaceholderAPI
description: Plugin for ToiletMC Server
website: https://toiletmc.net