name: ToiletCore
version: "${version}"
main: net.toiletmc.toiletcore.ToiletCore
api-version: "1.19"
authors: [ TheLittle_Yang, zty012 ]

softdepend:
  - "spark"
  - "AuthMe"
  - "PlaceholderAPI"

description: Plugin for ToiletMC Server
website: https://toiletmc.net

commands:
  toiletcore:
    aliases: [ tc ]
    permission: toiletcore.use
  shart:
    aliases: [ shit, poop, poo ]
    permission: toiletcore.shart.use
  hook:
    permission: toiletcore.hook.use
  cdk:
    permission: toiletcore.cdk.use

permissions:
  toiletcore.use:
    default: op
  toiletcore.admin:
    default: op
  toiletcore.shart.use:
    default: true
  toiletcore.shart.others:
    default: op
  toiletcore.hook.use:
    default: true
