name: ToiletCore
version: "${version}"
main: net.toiletmc.toiletcore.ToiletCore
api-version: "1.19"
authors: [TheLittle_Yang, zty012]

softdepend:
  - "spark"
  - "AuthMe"
  - "PlaceholderAPI"

description: Plugin for ToiletMC Server
website: https://toiletmc.net

commands:
  toiletcore:
    aliases: [tc]
    permission: toiletcore.use
  shart:
    aliases: [shit, poop, poo]
    permission: shart.use
  hook:
    permission: hook.use

permissions:
  toiletcore.use:
    default: op
  toiletcore.admin:
    default: op
  shart.use:
    default: true
  shart.others:
    default: op
  hook.use:
    default: true
