name: ToiletCore
version: "${version}"
main: net.toiletmc.toiletcore.ToiletCore
api-version: "1.21"
authors: [ TheLittle_Yang, zty012 ]

softdepend:
  - "AuthMe"
  - "spark"
  - "LuckPerms"

description: Plugin for ToiletMC Server
website: https://toiletmc.net

commands:
  toiletcore:
    aliases: [ tc ]
    permission: toiletcore.use
  shart:
    aliases: [ shit, poop, poo ]
    permission: toiletcore.use.shart
  hook:
    permission: toiletcore.use.hook
  cdk:
    permission: toiletcore.use.cdk
  qq:
    permission: toiletcore.use.qq

permissions:
  toiletcore.use:
    default: op
  toiletcore.admin:
    default: op
  toiletcore.admin.cdk:
    default: op
  toiletcore.use.shart:
    default: true
  toiletcore.use.shart.others:
    default: op
  toiletcore.use.hook:
    default: true
  toiletcore.use.cdk:
    default: true
  toiletcore.use.qq:
    default: true
